/**
 * Copy shared/ into the two places that can actually load it.
 *
 * An MV3 service worker can only import from inside the extension directory,
 * and a Worker's static assets directory only serves what is under it. Neither
 * can reach a sibling folder, so the one source of truth gets copied into both
 * and the copies are committed - that way `Load unpacked` works from a fresh
 * clone with no npm install, which is what a judge will actually do.
 *
 * This is the only build step in the project. Keep it that way.
 */

import { cp, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "shared");
const targets = [
  join(root, "extension", "shared"),
  join(root, "web", "public", "vendor", "shared"),
];

const NOTICE = `Generated by \`npm run sync-shared\` from /shared. Do not edit these copies.\n`;

const files = (await readdir(source)).filter((f) => f.endsWith(".js"));
if (files.length === 0) throw new Error("shared/ has no .js files to sync");

await spliceMatchingIntoContentScript(root);

for (const target of targets) {
  await mkdir(target, { recursive: true });
  for (const file of files) await cp(join(source, file), join(target, file));
  await writeFile(join(target, "README.md"), NOTICE);
  console.log(`synced ${files.length} file(s) -> ${target.replace(`${root}/`, "")}`);
}

/**
 * Splice shared/matching.js into the content script.
 *
 * The content script is injected as a file, not as a module graph, so it cannot
 * import anything - but the matching logic genuinely is the same problem in
 * both places and a second copy would drift. Generating one from the other
 * keeps a single source of truth while leaving the committed file loadable with
 * no build, which is what `Load unpacked` needs.
 */
async function spliceMatchingIntoContentScript(root) {
  const scriptPath = join(root, "extension", "content-agent.js");
  const script = await readFile(scriptPath, "utf8");
  const source = await readFile(join(root, "shared", "matching.js"), "utf8");

  const START = "// AALTO:MATCHING-START";
  const END = "// AALTO:MATCHING-END";
  const from = script.indexOf(START);
  const to = script.indexOf(END);
  if (from === -1 || to === -1) throw new Error("content-agent.js is missing its splice markers");

  // Strip the module's own header comment and turn its exports into plain
  // declarations. Nothing else about the code changes.
  const body = source
    .slice(source.indexOf("*/") + 2)
    .replace(/^export /gm, "")
    .trim();

  const next = `${script.slice(0, from + START.length)}\n${body}\n${script.slice(to)}`;
  if (next !== script) {
    await writeFile(scriptPath, next);
    console.log("spliced shared/matching.js -> extension/content-agent.js");
  }
}
