/**
 * Copy shared/ into the two places that can load it. Neither an MV3 service
 * worker nor a Worker's assets directory can reach a sibling folder, so the one
 * source of truth is copied into both and the copies are committed - `Load
 * unpacked` then works from a fresh clone with no npm install.
 *
 * The only build step in the project. Keep it that way.
 */

import { cp, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "shared");
const targets = [
  join(root, "extension", "shared"),
  join(root, "web", "public", "vendor", "shared"),
];

const NOTICE = `Generated by \`npm run sync-shared\` from /shared. Do not edit these copies.\n`;

const files = (await readdir(source)).filter((f) => f.endsWith(".js"));
if (files.length === 0) throw new Error("shared/ has no .js files to sync");

const SPLICES = [
  { file: "matching.js", marker: "MATCHING" },
  { file: "page-nav.js", marker: "PAGENAV" },
];

await spliceIntoContentScript(root);

for (const target of targets) {
  await mkdir(target, { recursive: true });
  for (const file of files) await cp(join(source, file), join(target, file));
  await writeFile(join(target, "README.md"), NOTICE);
  console.log(`synced ${files.length} file(s) -> ${target.replace(`${root}/`, "")}`);
}

/**
 * A content script is injected as a file, not a module graph, so it cannot
 * import - but a second copy of shared DOM logic would drift. Generating the
 * content script's copy from the shared module keeps one source of truth and a
 * file that loads with no build. Order matters: page-nav uses matching.
 */
async function spliceIntoContentScript(root) {
  const scriptPath = join(root, "extension", "content-agent.js");
  let script = await readFile(scriptPath, "utf8");
  const before = script;

  for (const { file, marker } of SPLICES) {
    const START = `// AALTO:${marker}-START`;
    const END = `// AALTO:${marker}-END`;
    const from = script.indexOf(START);
    const to = script.indexOf(END);
    if (from === -1 || to === -1)
      throw new Error(`content-agent.js is missing its ${marker} markers`);

    const source = await readFile(join(root, "shared", file), "utf8");
    // Strip the header and the imports, and turn exports into plain
    // declarations - the spliced blocks share one scope instead.
    const body = source
      .slice(source.indexOf("*/") + 2)
      .replace(/^import .*;\n/gm, "")
      .replace(/^export /gm, "")
      .trim();
    script = `${script.slice(0, from + START.length)}\n${body}\n${script.slice(to)}`;
  }

  if (script !== before) {
    await writeFile(scriptPath, script);
    console.log("spliced shared modules -> extension/content-agent.js");
  }
}
